# Generated by Django 3.2.18 on 2023-04-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='owner',
            new_name='test',
        ),
    ]
