# Generated by Django 3.2.18 on 2023-05-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at']},
        ),
    ]
